### ISSUE TITLE
App crashes when instantiating HelpStack

### ISSUE THREAD

**Issue by rpparas** [happyfoxinc/helpstack-android#24]
We tried integrating HelpStack by following steps given on GitHub, but we kept getting the following errors:

04-03 13:54:22.054 4638-4638/com.playerline.android E/AndroidRuntime﹕ FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.playerline.android/com.tenmiles.helpstack.activities.HomeActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1967)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4448)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.tenmiles.helpstack.activities.HSActivityParent.onCreate(HSActivityParent.java:48)
at com.tenmiles.helpstack.activities.HomeActivity.onCreate(HomeActivity.java:46)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4448)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)

I'm guessing it has something to do with the App Theme, which in our case is Theme.AppCompat.NoActionBar. Should I be looking at some other area?

**Comment by anirudh24seven** [comment]
Hey. Yeah. I verified and this does happen with NoActionBar. I guess this is because NoActionBar is available only on API v20+ but HelpStack has been built & tested all along only for version 19.

We make quite a few calls on methods chained to getSupportActionBar() without checking it for null, which is why this bug appears.

Possible solutions:
1. HelpStack should check all calls of methods chained to getSupportActionBar() and allow them to run only if getSupportActionBar() != null.
2. You can use a different App Theme until this problem is fixed.

**Comment by Abhishek-lodha** [comment]
Hi, I am also facing this issue. I am using 1.1.2 version of helpstack and have tried a different theme for HelpStack and mentioned the respective activities in manifest. [As here](https://github.com/happyfoxinc/helpstack-android/issues/35)
