### ISSUE TITLE
null pointer exception when trying to launch helpstack

### ISSUE THREAD

**Issue by quezak** [happyfoxinc/helpstack-android#35]
When trying to open HelpStack following the installation instructions, I get a null pointer exception following a call to `getSupportActionBar()` in your activity. I don't see any calls to `setSupportActionBar` in your activity, maybe is that the reason?

Testing on Android 5.1, app's minimum is 4.0.

My setup:

```
        helpStack = HSHelpStack.getInstance(context);
        HSEmailGear hsGear = new HSEmailGear("support@****", R.xml.test_faq_articles);
        helpStack.setGear(hsGear);
```

My launch line:

```
        HSHelpStack.getInstance(getActivity()).showHelp(getActivity());
```

Stack trace:

```
[...]
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setHomeButtonEnabled(boolean)' on a null object reference
    at com.tenmiles.helpstack.activities.HSActivityParent.onCreate(HSActivityParent.java:48)
    at com.tenmiles.helpstack.activities.HomeActivity.onCreate(HomeActivity.java:45)
    at android.app.Activity.performCreate(Activity.java:6088)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2416) 
    at android.app.ActivityThread.access$900(ActivityThread.java:154) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1322) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:135) 
    at android.app.ActivityThread.main(ActivityThread.java:5300) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by menasheh** [comment]
For me, getActivity() isn't recognized.

**Comment by quezak** [comment]
I'm launching this from a `Fragment` subclass (same way as the example
does), and `getActivity()` is a `Fragment`'s method.
I also tried using the instance of my application as context, but the
result didn't change.

**Comment by aayaffe** [comment]
I still have the same issue described here

**Comment by julianonunes** [comment]
The problem may be related to the theme you are using. If you choose a theme like Theme.AppCompat.Light.NoActionBar for the entire Application, then you may have to add each HelpStack activity to your AndroidManifest file specifying a different Theme, enabling the ActionBar.

**Comment by shahkumarrakesh** [comment]
Can you tell me how to add each activity in the manifest

**Comment by julianonunes** [comment]
In styles.xml I've declared AppThemeWithActionBar:

```
    <style name="AppThemeWithActionBar" parent="Theme.AppCompat.Light">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:textColorPrimary">#ffffffff</item>
        <item name="android:textColorSecondary">#ffffffff</item>

    </style> 
```

Then in the AndroidManifest I've added

```
<activity android:name="com.tenmiles.helpstack.activities.HomeActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.ArticleActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.EditAttachmentActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.ImageAttachmentDisplayActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.IssueDetailActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.NewIssueActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.NewUserActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
        <activity android:name="com.tenmiles.helpstack.activities.SectionActivity"
            android:theme="@style/AppThemeWithActionBar"></activity>
```

**Comment by SureshCS-50** [comment]
Issue has been fixed, You can use the code from the master branch.
