### ISSUE TITLE
{"error":"Couldn't authenticate you"}

### ISSUE THREAD

**Issue by dranandrao** [happyfoxinc/helpstack-android#38]
I am getting this error while connecting to Zendesk gear.

This is the stacktrace.
10-25 12:36:47.219 23480-32509/com.example.drrao.helpstack E/Volley: [678] BasicNetwork.performRequest: Unexpected response code 401 for https://ireff.zendesk.com/api/v2/help_center/sections.json
10-25 12:36:47.969 23480-32509/com.example.drrao.helpstack E/Volley: [678] BasicNetwork.performRequest: Unexpected response code 401 for https://ireff.zendesk.com/api/v2/help_center/sections.json
10-25 12:36:48.229 23480-32509/com.example.drrao.helpstack E/Volley: [678] BasicNetwork.performRequest: Unexpected response code 401 for https://ireff.zendesk.com/api/v2/help_center/sections.json
10-25 12:36:48.229 23480-23480/com.example.drrao.helpstack E/HSHelpStack: Error occurred when executing Fetching KB articles
10-25 12:36:48.229 23480-23480/com.example.drrao.helpstack E/HSHelpStack: com.android.volley.AuthFailureError
10-25 12:36:48.229 23480-23480/com.example.drrao.helpstack E/HSHelpStack: {"error":"Couldn't authenticate you"}
10-25 12:36:48.229 23480-23480/com.example.drrao.helpstack W/System.err: com.android.volley.AuthFailureError
10-25 12:36:48.239 23480-23480/com.example.drrao.helpstack W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:153)
10-25 12:36:48.239 23480-23480/com.example.drrao.helpstack W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)

When I make a call
 HSHelpStack.getInstance(MyActivity.this).showHelp(MyActivity.this);
I get a popup stating Error in fetching Articles and Issues.

**Comment by nmohideen** [comment]
This was due to a authentication requirement on the Zendesk Help Center. Solved by removing the authentication requirement.

**Comment by ccsavvy** [comment]
Hey @nmohideen , how did you remove it? I can't find a way how to remove it.
