### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.tenmiles.helpstack.logic.HSGear.haveImplementedKBFetching()' on a null object reference

### ISSUE THREAD

**Issue by photog0411** [happyfoxinc/helpstack-android#45]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tenmiles.helpstack.logic.HSGear.haveImplementedKBFetching()' on a null object reference
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.tenmiles.helpstack.logic.HSGear.haveImplementedKBFetching()' on a null object reference
                                                                     at com.tenmiles.helpstack.logic.HSSource.requestKBArticle(HSSource.java:110)
                                                                     at com.tenmiles.helpstack.fragments.HomeFragment.initializeView(HomeFragment.java:193)
                                                                     at com.tenmiles.helpstack.fragments.HomeFragment.onCreateView(HomeFragment.java:122)
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                     at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                     at android.app.Activity.performStart(Activity.java:6679)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)

**Comment by photog0411** [comment]
this is happening on nougat

**Comment by photog0411** [comment]
tested on 3 different devices, api levels 22, 23 and 24, this null pointer exception in your files is happening on all 3 devices

**Comment by SureshCS-50** [comment]
Hi @photog0411 
Seems like you haven't set the gear.
Please check this [https://github.com/happyfoxinc/helpstack-android#setting-the-gear](https://github.com/happyfoxinc/helpstack-android#setting-the-gear)

**Comment by photog0411** [comment]
thank you suresh
