### ISSUE TITLE
Unable to start activity com.tenmiles.helpstack.activities.HomeActivity

### ISSUE THREAD

**Issue by mcaquet** [happyfoxinc/helpstack-android#57]
When I run the line 
`HSHelpStack.getInstance(getApplicationContext()).showHelp(this);`

I get the following error:
`Unable to start activity ComponentInfo{com.awox.smart.control/com.tenmiles.helpstack.activities.HomeActivity`

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setHomeButtonEnabled(boolean)' on a null object reference
        at com.tenmiles.helpstack.activities.HSActivityParent.onCreate(HSActivityParent.java:48)
        at com.tenmiles.helpstack.activities.HomeActivity.onCreate(HomeActivity.java:45)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)

```
Could you please help solving this problem ?

**Comment by SunStalker** [comment]
So do I, tested on Android 7 and 8

**Comment by bahaa-ka** [comment]
me to also on 5.1.1 api 22
